# Generated by Django 4.2.15 on 2024-09-20 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='url_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
