# Generated by Django 4.2.15 on 2024-09-23 14:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_dish_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='url_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
