# Generated by Django 4.2.15 on 2024-09-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservations',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablereservations',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
